DROP TABLE IF EXISTS markers CASCADE;

CREATE TABLE markers (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  image TEXT,
  longitude DOUBLE PRECISION ,
  latitude DOUBLE PRECISION,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE
);
